services:

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network
  
  mongo-seed:
    build: ./db
    depends_on:
      - mongo
    networks:
      - my-network
  
  backend:
    # build: ./backend
    build:
      context: ./backend
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks:
      - my-network

volumes:
  mongo-data:

networks:
  my-network: